# https://docs.astral.sh/ruff/rules/
[lint]
select = [
    "ERA",
    "BLE",
    "FBT",
    "A",
    "C4",
    "FIX",
    "ISC",
    "ICN",
    "G",
    "PIE",
    "T20",
    "RSE",
    "Q",
    "RET",
    "SIM",
    "ARG",
    "FLY",
    "C90",
    "N",
    "PERF",
    #"W",
    "RUF",
    "E",
    "F",
    "UP",
    "B",
    #"I",
	"PL",
	"S",

    # Doctstrings
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",

    #Type hinting
    "ANN"
]